services:
  db:
    image: neondatabase/neon_local:latest
    container_name: luzimarket-db
    ports:
      - "5432:5432"
    environment:
      NEON_API_KEY_FILE: /run/secrets/neon_api_key
      NEON_PROJECT_ID_FILE: /run/secrets/neon_project_id
      BRANCH_ID_FILE: /run/secrets/neon_branch_id
    secrets:
      - neon_api_key
      - neon_project_id
      - neon_branch_id
    # Optional: Persist a Neon branch per Git branch and across restarts
    # See: https://neon.com/docs/local/neon-local
    # volumes:
    #   - ./.neon_local/:/tmp/.neon_local
    #   - ./.git/HEAD:/tmp/.git/HEAD:ro,consistent

secrets:
  neon_api_key:
    file: ./tmp/secrets/neon_api_key.txt
  neon_project_id:
    file: ./tmp/secrets/neon_project_id.txt
  neon_branch_id:
    file: ./tmp/secrets/neon_branch_id.txt