version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/ecommerce
      - JWT_SECRET=your_jwt_secret
      - CORS_ORIGIN=http://localhost:5173
      - STRIPE_SECRET_KEY=your_stripe_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data:
    external: false