export default ({ env }) => ({
    'api-token': {
      enabled: true,
      config: {
        tokens: [
          {
            name: 'Backend Access Token',
            description: 'Token for backend service to access Strapi API',
            type: 'full-access',
            token: env('STRAPI_API_TOKEN'),
          },
        ],
      },
    },
    'users-permissions': {
        enabled: true,
        config: {
            jwt: {
                expiresIn: '7d',
            },
            jwtSecret: env('JWT_SECRET'),
            grant: {
                email: {
                    enabled: true,
                    icon: 'envelope',
                },
                discord: {
                    enabled: false,
                    icon: 'discord',
                    key: '',
                    secret: '',
                    callback: '/auth/discord/callback',
                    scope: ['identify', 'email'],
                },
                facebook: {
                    enabled: false,
                    icon: 'facebook-square',
                    key: '',
                    secret: '',
                    callback: '/auth/facebook/callback',
                    scope: ['email'],
                },
                google: {
                    enabled: false,
                    icon: 'google',
                    key: '',
                    secret: '',
                    callback: '/auth/google/callback',
                    scope: ['email'],
                },
                github: {
                    enabled: false,
                    icon: 'github',
                    key: '',
                    secret: '',
                    callback: '/auth/github/callback',
                    scope: ['user', 'user:email'],
                },
                microsoft: {
                    enabled: false,
                    icon: 'windows',
                    key: '',
                    secret: '',
                    callback: '/auth/microsoft/callback',
                    scope: ['user.read'],
                },
                twitter: {
                    enabled: false,
                    icon: 'twitter',
                    key: '',
                    secret: '',
                    callback: '/auth/twitter/callback',
                },
                instagram: {
                    enabled: false,
                    icon: 'instagram',
                    key: '',
                    secret: '',
                    callback: '/auth/instagram/callback',
                    scope: ['user_profile'],
                },
                vk: {
                    enabled: false,
                    icon: 'vk',
                    key: '',
                    secret: '',
                    callback: '/auth/vk/callback',
                    scope: ['email'],
                },
                twitch: {
                    enabled: false,
                    icon: 'twitch',
                    key: '',
                    secret: '',
                    callback: '/auth/twitch/callback',
                    scope: ['user:read:email'],
                },
                linkedin: {
                    enabled: false,
                    icon: 'linkedin',
                    key: '',
                    secret: '',
                    callback: '/auth/linkedin/callback',
                    scope: ['r_liteprofile', 'r_emailaddress'],
                },
                cognito: {
                    enabled: false,
                    icon: 'aws',
                    key: '',
                    secret: '',
                    subdomain: 'my.subdomain.com',
                    callback: '/auth/cognito/callback',
                    scope: ['email', 'openid', 'profile'],
                },
                reddit: {
                    enabled: false,
                    icon: 'reddit',
                    key: '',
                    secret: '',
                    state: true,
                    callback: '/auth/reddit/callback',
                    scope: ['identity'],
                },
                auth0: {
                    enabled: false,
                    icon: '',
                    key: '',
                    secret: '',
                    subdomain: 'my-tenant.eu',
                    callback: '/auth/auth0/callback',
                    scope: ['openid', 'email', 'profile'],
                },
                cas: {
                    enabled: false,
                    icon: 'book',
                    key: '',
                    secret: '',
                    callback: '/auth/cas/callback',
                    scope: ['openid email'],
                    subdomain: 'my.subdomain.com/cas',
                },
            },
        },
    },
});
