name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]

    env:
      # App/test server
      PORT: 3000
      CI: true
      PW_WORKERS: 2
      # Enable all Playwright projects in CI (see playwright.config.ts)
      CI_ALL_BROWSERS: 1
      # Core secrets (exposed from repo secrets)
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      # Optional integrations (present in repo secrets)
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_TOKEN }}
      # Pass threshold: Allow CI to pass with 95% of tests passing
      PLAYWRIGHT_PASS_THRESHOLD: 95

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Apply database schema
        run: npm run db:push

      - name: Run Playwright tests (LLM)
        run: npm run test -- --project="${{ matrix.project }}"
        continue-on-error: true

      - name: Check pass threshold (95%)
        run: node e2e/scripts/check-pass-threshold.js

      - name: Upload LLM artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: llm-test-artifacts-${{ matrix.project }}
          path: |
            tmp/test-results.json
            tmp/junit-results.xml
          if-no-files-found: warn

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          if-no-files-found: warn
